# Generated by Django 5.1.6 on 2025-04-01 10:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carros', '0010_delete_inspecao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ultima_inspecao', models.DateField(default=django.utils.timezone.now)),
                ('data_proxima_inspecao', models.DateField(default=django.utils.timezone.now)),
                ('data_proxima_inspecao_obrigatoria', models.DateField(default=django.utils.timezone.now)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Pendente', 'Pendente')], default='Pendente', max_length=20)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecoes', to='carros.carro')),
            ],
            options={
                'permissions': [('pode_gerenciar_inspecoes', 'Pode gerenciar inspeções')],
            },
        ),
    ]
