# Generated by Django 5.1.6 on 2025-04-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_relatorio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspecao',
            old_name='data_proxima_inspecao',
            new_name='data_proxima_revisao',
        ),
    ]
