# Generated by Django 5.1.6 on 2025-03-25 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carros', '0009_alter_inspecao_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha'), ('pendente', 'Pendente')], default='pendente', max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('aluguel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transacao', to='carros.aluguel')),
            ],
        ),
    ]
