# Generated by Django 5.1.6 on 2025-03-11 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_inspecao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecao',
            name='data_inspecao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
