# Generated by Django 5.1.6 on 2025-03-12 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_alter_inspecao_data_inspecao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Confirmado', 'Confirmado'), ('Em Andamento', 'Em Andamento'), ('Concluido', 'Concluido'), ('Cancelado', 'Cancelado')], default='Confirmado', max_length=20)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluguéis', to='carros.carro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluguéis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
