# Generated by Django 5.1.6 on 2025-03-20 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0008_carro_categoria_carro_qtd_pessoas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspecao',
            options={'permissions': [('pode_gerenciar_inspecoes', 'Pode gerenciar inspeções')]},
        ),
    ]
