# Generated by Django 5.1.6 on 2025-03-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0007_carro_combustivel_carro_transmissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='categoria',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande'), ('suv', 'SUV'), ('luxo', 'Luxo')], default='medio', max_length=20),
        ),
        migrations.AddField(
            model_name='carro',
            name='qtd_pessoas',
            field=models.CharField(choices=[('1-4', '1-4'), ('5-6', '5-6'), ('+7', '+7')], default='1-4', max_length=20),
        ),
        migrations.AddField(
            model_name='carro',
            name='tipo_veiculos',
            field=models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('motorhome', 'MotorHome')], default='carro', max_length=20),
        ),
        migrations.AlterField(
            model_name='carro',
            name='combustivel',
            field=models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diesel'), ('eletrico', 'Elétrico'), ('hibrido', 'Híbrido'), ('gpl', 'GPL')], default='gasolina', max_length=20),
        ),
        migrations.AlterField(
            model_name='carro',
            name='transmissao',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], default='manual', max_length=20),
        ),
    ]
