# Generated by Django 5.1.6 on 2025-04-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0009_alter_inspecao_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inspecao',
        ),
    ]
