# Generated by Django 5.1.6 on 2025-04-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0010_delete_inspecao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='ano',
        ),
    ]
